### ISSUE TITLE
BUG - disable freshness tests for disabled source tables

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_greenhouse_source#12]
**Are you a current Fivetran customer?** 

i work @ fivetran 

**Describe the bug**

freshness tests are producing errors for folks who do not have various source models and are disabling package logic related to them. 

need to incorporate changes we made to hubspot basically https://github.com/fivetran/dbt_hubspot_source/pull/43

**Expected behavior**

if you aren't using a source table, a freshness test should not be run on it 

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this as the merge resolves the issue
