### ISSUE TITLE
[Feature] Update docs and seeds

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_greenhouse_source#26]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Seeds and docs contain references to customs columns in `application` and `job` tables. Remove from seeds and docs for a clean docs regen. 

Also review docs for any columns missing descriptions.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
this has been addressed in the mentioned release!

**Comment by fivetran-joemarkiewicz** [comment]
Testing comment after closing.
